// src/lib/audit-log-data.ts
import type { AuditLog } from '@/types';

export let auditLogs: AuditLog[] = [
  {
    id: 'log-001',
    userId: 'user-supplier',
    action: 'product.created',
    entityId: 'pp-001',
    details: { name: 'Eco-Friendly Smart Watch' },
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'log-002',
    userId: 'user-supplier',
    action: 'passport.submitted',
    entityId: 'pp-001',
    details: {},
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000 + 10000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000 + 10000).toISOString(),
  },
  {
    id: 'log-003',
    userId: 'user-auditor',
    action: 'passport.approved',
    entityId: 'pp-001',
    details: { txHash: '0x123abc' },
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
   {
    id: 'log-004',
    userId: 'user-developer',
    action: 'webhook.delivery.success',
    entityId: 'wh-001',
    details: {
      event: 'product.published',
      statusCode: 200,
      productId: 'pp-001',
      url: 'https://api.example.com/v1/norruva-hooks',
      payload: '{"event":"product.published","payload":{"id":"pp-001", "name":"Eco-Friendly Smart Watch"}}',
      latencyMs: 120,
    },
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000 + 5000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000 + 5000).toISOString(),
  },
  {
    id: 'log-005',
    userId: 'user-developer',
    action: 'webhook.delivery.failure',
    entityId: 'wh-002',
    details: {
      event: 'compliance.failed',
      statusCode: 503,
      error: 'Service Unavailable',
      productId: 'pp-004',
      url: 'https://alerts.example.com/dpp-compliance-failures',
      payload: '{"event":"compliance.failed","payload":{"id":"pp-004", "name":"Leather Handbag"}}',
      latencyMs: 55,
    },
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'log-006',
    userId: 'user-service',
    action: 'ticket.created',
    entityId: 'tkt-001',
    details: { issue: 'Screen flickering' },
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'log-007',
    userId: 'system',
    action: 'credits.minted',
    entityId: 'pp-001',
    details: {
      amount: 10,
      recipient: 'user-recycler'
    },
    createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'log-api-01',
    userId: 'user-developer',
    action: 'api.get',
    entityId: 'pp-001',
    details: {
      endpoint: '/api/v2/products/pp-001',
      status: 200,
      method: 'GET',
      latencyMs: 45,
    },
    createdAt: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
  },
  {
    id: 'log-api-02',
    userId: 'user-developer',
    action: 'api.post',
    entityId: 'pp-002',
    details: {
      endpoint: '/api/v2/products',
      status: 201,
      method: 'POST',
      latencyMs: 180,
    },
    createdAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
  },
  {
    id: 'log-api-03',
    userId: 'user-developer',
    action: 'api.get',
    entityId: 'non-existent',
    details: {
      endpoint: '/api/v2/products/non-existent',
      status: 404,
      method: 'GET',
      latencyMs: 25,
    },
    createdAt: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
  },
];
