// src/lib/data.ts
import type { Product } from './types';

export let products: Product[] = [
  {
    id: 'pp-001',
    companyId: 'comp-02',
    gtin: '09501101420014',
    productName: 'Eco-Friendly Smart Watch Series 5',
    productDescription:
      'A sleek smartwatch made from recycled aluminum and sustainable materials, featuring a long-lasting battery and comprehensive health tracking.',
    productImage: 'https://placehold.co/400x400.png',
    category: 'Electronics',
    supplier: 'GreenTech Supplies',
    status: 'Published',
    lastUpdated: '2024-07-21T10:00:00Z',
    createdAt: '2024-07-01T10:00:00Z',
    updatedAt: '2024-07-21T10:00:00Z',
    compliancePathId: 'cp-electronics-01',
    manualUrl: 'https://example.com/manual-sw5.pdf',
    conformityDocUrl: 'https://example.com/doc-sw5.pdf',
    materials: [
      {
        name: 'Recycled Aluminum',
        percentage: 60,
        recycledContent: 100,
        origin: 'Germany',
      },
      {
        name: 'Fluoroelastomer',
        percentage: 20,
        recycledContent: 0,
        origin: 'China',
      },
      { name: 'Gorilla Glass', percentage: 20, origin: 'USA' },
    ],
    manufacturing: {
      facility: 'Eco-Factory 1',
      country: 'Germany',
      emissionsKgCo2e: 15.5,
    },
    packaging: {
      type: 'Recycled Cardboard',
      recyclable: true,
      recycledContent: 100,
      weight: 50,
    },
    lifecycle: {
      carbonFootprint: 15.5,
      carbonFootprintMethod: 'ISO 14067',
      repairabilityScore: 7,
      expectedLifespan: 5,
      energyEfficiencyClass: 'A',
      recyclingInstructions:
        'Remove band before recycling main body at a certified e-waste facility. Battery must be removed by a professional.',
    },
    battery: {
      type: 'Lithium-ion',
      capacityMah: 3110,
      voltage: 3.83,
      isRemovable: false,
    },
    certifications: [
      { name: 'CE', issuer: 'TÜV SÜD' },
      { name: 'RoHS Compliant', issuer: 'Intertek' },
      { name: 'ISO 14001', issuer: 'Eco-Factory 1' },
    ],
    compliance: {
      rohsCompliant: true,
      reachSVHC: false,
      ceMarked: true,
      weeeRegistered: true,
      weeeRegistrationNumber: 'DE 12345678',
    },
    verificationStatus: 'Verified',
    lastVerificationDate: '2024-07-22T14:00:00Z',
    blockchainProof: {
      txHash: '0x123abc456def7890123abc456def7890123abc456def7890123abc456def',
      explorerUrl:
        'https://www.oklink.com/amoy/tx/0x123abc456def7890123abc456def7890123abc456def7890123abc456def',
      blockHeight: 51842069,
    },
    ebsiVcId: 'did:ebsi:z2d5i1d9o8f7g6h5j4k3l2m1n0p',
    qrLabelText:
      'Verified to meet EU standards for sustainability and safety, this watch is crafted from 100% recycled aluminum.',
    sustainability: {
      score: 85,
      environmental: 90,
      social: 80,
      governance: 88,
      isCompliant: true,
      complianceSummary:
        'Product is compliant with all known rules for its category.',
      gaps: [],
      classification: {
        esgCategory: 'Circular Design',
        riskScore: 2,
      },
      lifecycleAnalysis: {
        carbonFootprint: {
          value: 15.5,
          unit: 'kg CO2-eq',
          summary:
            'Estimated based on recycled aluminum body and typical electronics manufacturing in Germany.',
        },
        lifecycleStages: {
          manufacturing:
            'The highest impact comes from manufacturing the display and battery. Use of recycled aluminum significantly reduces this.',
          usePhase:
            'Energy consumption is low due to an efficient ARM-based processor. Impact primarily depends on user charging habits.',
          endOfLife:
            'High recyclability potential if disassembled correctly. The non-removable battery poses a challenge.',
        },
        highestImpactStage: 'Manufacturing',
        improvementOpportunities: [
          'Implement a take-back program for battery replacement and recycling.',
          'Source display manufacturing from facilities powered by renewable energy.',
          'Offer a version with a bio-based polymer band instead of fluoroelastomer.',
        ],
      },
    },
    endOfLifeStatus: 'Active',
    dataQualityWarnings: [],
    completenessScore: 95,
  },
  {
    id: 'pp-002',
    companyId: 'comp-03',
    gtin: '01234567890123',
    productName: 'Pro-Grade 4K Drone',
    productDescription:
      'A professional-grade quadcopter with a 4K camera, 30-minute flight time, and advanced obstacle avoidance sensors.',
    productImage: 'https://placehold.co/400x400.png',
    category: 'Electronics',
    supplier: 'AeroDynamics Inc.',
    status: 'Published',
    lastUpdated: '2024-07-19T11:00:00Z',
    createdAt: '2024-07-02T11:00:00Z',
    updatedAt: '2024-07-19T11:00:00Z',
    compliancePathId: 'cp-electronics-01',
    materials: [
      {
        name: 'Carbon Fiber',
        percentage: 50,
        recycledContent: 10,
        origin: 'USA',
      },
      {
        name: 'ABS Plastic',
        percentage: 30,
        recycledContent: 5,
        origin: 'South Korea',
      },
    ],
    manufacturing: {
      facility: 'Aero Plant 1',
      country: 'USA',
      emissionsKgCo2e: 25.0,
    },
    packaging: { type: 'Molded Plastic', recyclable: false, weight: 150 },
    lifecycle: {
      repairabilityScore: 5,
      expectedLifespan: 3,
    },
    battery: {
      type: 'Lithium Polymer',
      capacityMah: 5200,
      voltage: 15.2,
      isRemovable: true,
    },
    certifications: [{ name: 'FCC', issuer: 'FCC' }],
    compliance: {
      rohsCompliant: true,
      reachSVHC: true,
      scipReference: 'mock-scip-ref-12345',
      ceMarked: true,
    },
    verificationStatus: 'Pending',
    sustainability: {
      score: 68,
      environmental: 65,
      social: 70,
      governance: 75,
      isCompliant: false,
      complianceSummary: 'Awaiting auditor review.',
    },
    endOfLifeStatus: 'Active',
    dataQualityWarnings: [
      {
        field: 'materials.percentage',
        warning:
          'Material percentages add up to 80%. Consider adding battery weight to composition.',
      },
    ],
    completenessScore: 70,
  },
  {
    id: 'pp-003',
    companyId: 'comp-02',
    gtin: '05556667778882',
    productName: 'Organic Cotton T-Shirt',
    productDescription:
      'A soft, breathable t-shirt made from 100% GOTS-certified organic cotton, ethically produced in a fair trade factory.',
    productImage: 'https://placehold.co/400x400.png',
    category: 'Fashion',
    supplier: 'GreenTech Supplies',
    status: 'Draft',
    lastUpdated: '2024-07-20T12:00:00Z',
    createdAt: '2024-07-03T12:00:00Z',
    updatedAt: '2024-07-20T12:00:00Z',
    compliancePathId: 'cp-fashion-01',
    materials: [
      {
        name: 'Organic Cotton',
        percentage: 100,
        recycledContent: 0,
        origin: 'India',
      },
    ],
    manufacturing: {
      facility: 'Sustainable Threads Mill',
      country: 'India',
    },
    packaging: { type: 'Compostable Bag', recyclable: true, weight: 10 },
    lifecycle: {
      expectedLifespan: 2,
    },
    certifications: [
      { name: 'GOTS', issuer: 'Control Union' },
      { name: 'Fair Trade Certified', issuer: 'Fair Trade USA' },
    ],
    compliance: {
      rohsCompliant: true,
      reachSVHC: false,
    },
    verificationStatus: 'Not Submitted',
    sustainability: {
      score: 92,
      environmental: 95,
      social: 98,
      governance: 80,
      isCompliant: false,
      complianceSummary: '',
    },
    endOfLifeStatus: 'Active',
    dataQualityWarnings: [],
    completenessScore: 80,
  },
  {
    id: 'pp-004',
    companyId: 'comp-02',
    gtin: '04443332221115',
    productName: 'Recycled Polyester Jacket',
    productDescription:
      'A lightweight, water-resistant jacket made from recycled plastic bottles. Not compliant with the GOTS fashion path.',
    productImage: 'https://placehold.co/400x400.png',
    category: 'Fashion',
    supplier: 'GreenTech Supplies',
    status: 'Published',
    lastUpdated: '2024-07-18T13:00:00Z',
    createdAt: '2024-07-04T13:00:00Z',
    updatedAt: '2024-07-18T13:00:00Z',
    compliancePathId: 'cp-fashion-01',
    materials: [
      {
        name: 'Recycled Polyester',
        percentage: 100,
        recycledContent: 100,
        origin: 'Taiwan',
      },
    ],
    manufacturing: { facility: 'EcoFabric Taiwan', country: 'Taiwan' },
    packaging: { type: 'Plastic Bag', recyclable: false, weight: 30 },
    certifications: [],
    compliance: {
      rohsCompliant: true,
      reachSVHC: false,
    },
    verificationStatus: 'Failed',
    lastVerificationDate: '2024-07-19T10:00:00Z',
    sustainability: {
      score: 55,
      environmental: 70,
      social: 50,
      governance: 60,
      isCompliant: false,
      complianceSummary:
        "Product failed verification with 1 issue(s). Contains banned material 'Polyester'.",
      gaps: [
        {
          regulation: 'Global Organic Textile Standard',
          issue: "Product contains a banned material: 'Recycled Polyester'.",
        },
      ],
    },
    endOfLifeStatus: 'Recycled',
    dataQualityWarnings: [
      {
        field: 'materials',
        warning:
          'The product category is "Fashion" but it contains "Polyester". While common, this material is banned by the selected compliance path.',
      },
    ],
    completenessScore: 85,
  },
  {
    id: 'pp-005',
    companyId: 'comp-03',
    gtin: '01122334455667',
    productName: 'Modular Shelving Unit',
    productDescription:
      'A versatile shelving unit made from sustainably sourced bamboo and powder-coated steel.',
    productImage: 'https://placehold.co/400x400.png',
    category: 'Home Goods',
    supplier: 'AeroDynamics Inc.',
    status: 'Archived',
    lastUpdated: '2024-07-15T15:00:00Z',
    createdAt: '2024-07-05T15:00:00Z',
    updatedAt: '2024-07-15T15:00:00Z',
    compliancePathId: 'cp-homegoods-01',
    manualUrl: 'https://example.com/manual-shelving.pdf',
    materials: [
      { name: 'Bamboo', percentage: 70, origin: 'China' },
      { name: 'Steel', percentage: 30, origin: 'USA' },
    ],
    manufacturing: { facility: 'EcoHome Workshop', country: 'China' },
    packaging: { type: 'Cardboard Box', recyclable: true, weight: 500 },
    lifecycle: {
      repairabilityScore: 9,
      expectedLifespan: 15,
    },
    certifications: [{ name: 'FSC Certified', issuer: 'FSC' }],
    compliance: {
      rohsCompliant: true,
      reachSVHC: false,
    },
    verificationStatus: 'Verified',
    blockchainProof: {
      txHash: '0x456def7890123abc456def7890123abc456def7890123abc456def123abc',
      explorerUrl:
        'https://www.oklink.com/amoy/tx/0x456def7890123abc456def7890123abc456def7890123abc456def123abc',
      blockHeight: 51842070,
    },
    ebsiVcId: 'did:ebsi:z7i1r9t6g3f1e9c7b5a3z1y9x7w5v3u1',
    sustainability: {
      score: 78,
      environmental: 85,
      social: 70,
      governance: 75,
      isCompliant: false,
      complianceSummary: '',
    },
    endOfLifeStatus: 'Disposed',
    dataQualityWarnings: [],
    completenessScore: 100,
  },
  {
    id: 'pp-006',
    companyId: 'comp-03',
    gtin: '08887776665551',
    productName: 'Smart Nutrient Tracker Bottle',
    productDescription:
      'A smart water bottle that tracks your hydration and nutrient intake via a connected app. Made with food-grade stainless steel.',
    productImage: 'https://placehold.co/400x400.png',
    category: 'Home Goods',
    supplier: 'AeroDynamics Inc.',
    status: 'Published',
    lastUpdated: '2024-07-22T11:00:00Z',
    createdAt: '2024-07-10T11:00:00Z',
    updatedAt: '2024-07-22T11:00:00Z',
    compliancePathId: 'cp-homegoods-01',
    materials: [
      { name: '304 Stainless Steel', percentage: 80, origin: 'China' },
      { name: 'BPA-Free Plastic (Lid)', percentage: 20, origin: 'USA' },
    ],
    manufacturing: { facility: 'SmartHome Goods', country: 'USA' },
    packaging: { type: 'Recycled Paper Tube', recyclable: true, weight: 80 },
    lifecycle: {
      repairabilityScore: 4,
      expectedLifespan: 2,
    },
    battery: {
      type: 'Lithium-ion',
      capacityMah: 500,
      isRemovable: false,
    },
    certifications: [],
    compliance: {
      foodContactSafe: true,
      foodContactComplianceStandard: 'FDA 21 CFR',
    },
    verificationStatus: 'Verified',
    lastVerificationDate: '2024-07-22T15:00:00Z',
    sustainability: {
      score: 75,
      environmental: 70,
      social: 80,
      governance: 78,
      isCompliant: true,
      complianceSummary: 'Product meets all safety standards for its category.',
      gaps: [],
    },
    endOfLifeStatus: 'Active',
    dataQualityWarnings: [],
    completenessScore: 90,
  },
  {
    id: 'pp-007',
    companyId: 'comp-02',
    gtin: '09998887776668',
    productName: 'Artisan Leather Hiking Boots',
    productDescription:
      'Durable, handcrafted hiking boots made from responsibly sourced full-grain leather and natural rubber outsoles.',
    productImage: 'https://placehold.co/400x400.png',
    category: 'Fashion',
    supplier: 'GreenTech Supplies',
    status: 'Published',
    lastUpdated: '2024-07-23T09:00:00Z',
    createdAt: '2024-07-11T09:00:00Z',
    updatedAt: '2024-07-23T09:00:00Z',
    compliancePathId: 'cp-fashion-02',
    materials: [
      { name: 'Full-grain Leather', percentage: 70, origin: 'Brazil' },
      { name: 'Natural Rubber', percentage: 25, origin: 'Vietnam' },
      { name: 'Cork (Insole)', percentage: 5, origin: 'Portugal' },
    ],
    manufacturing: { facility: 'Artisan Footwear Co.', country: 'Portugal' },
    packaging: {
      type: 'Cardboard Box',
      recyclable: true,
      weight: 200,
      recycledContent: 80,
    },
    lifecycle: {
      repairabilityScore: 8,
      expectedLifespan: 10,
    },
    certifications: [{ name: 'Leather Working Group (Gold)', issuer: 'LWG' }],
    compliance: {
      reachSVHC: false,
      eudrCompliant: true,
      eudrDiligenceId: 'DDS-2024-XYZ-123',
    },
    verificationStatus: 'Verified',
    lastVerificationDate: '2024-07-23T11:00:00Z',
    sustainability: {
      score: 88,
      environmental: 85,
      social: 92,
      governance: 85,
      isCompliant: true,
      complianceSummary: 'Product complies with REACH and EUDR requirements.',
      gaps: [],
    },
    endOfLifeStatus: 'Active',
    dataQualityWarnings: [],
    completenessScore: 100,
  },
];
