
// src/lib/data.ts
import type { Product, BlockchainProof } from '@/types';

const now = new Date();
export let products: Product[] = [
  {
    id: 'pp-001',
    companyId: 'comp-eco',
    gtin: '09501101530003',
    productName: 'Eco-Friendly Smart Watch Series 5',
    productDescription:
      'A state-of-the-art smart watch made from 100% recycled aluminum and ethically sourced components. Features advanced health tracking and a 3-day battery life.',
    productImage: 'https://placehold.co/600x400.png',
    category: 'Electronics',
    supplier: 'Eco Innovate Ltd.',
    status: 'Published',
    compliancePathId: 'cp-electronics-01',
    manualUrl: 'https://example.com/manual.pdf',
    manualFileName: 'smartwatch-manual-v5.pdf',
    manualFileSize: 1258291,
    manualFileHash: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
    modelHotspots: [
      { position: [0, 0.5, 0], data: { name: 'Watch Face', material: 'Gorilla Glass' }, interactionType: 'showInfo' },
      { position: [0.5, 0, 0], data: { name: 'Crown', material: 'Recycled Aluminum' }, interactionType: 'showInfo' },
    ],
    createdAt: new Date(new Date(now).setDate(now.getDate() - 2)).toISOString(),
    updatedAt: new Date(new Date(now).setDate(now.getDate() - 1)).toISOString(),
    lastUpdated: new Date(
      new Date(now).setDate(now.getDate() - 1),
    ).toISOString(),
    materials: [
      {
        name: 'Recycled Aluminum',
        percentage: 60,
        recycledContent: 100,
        origin: 'Germany',
      },
      {
        name: 'Gorilla Glass',
        percentage: 15,
        recycledContent: 0,
        origin: 'USA',
      },
      {
        name: 'Silicone',
        percentage: 25,
        recycledContent: 50,
        origin: 'South Korea',
      },
    ],
    manufacturing: {
      facility: 'Eco-Factory 1',
      country: 'Germany',
      emissionsKgCo2e: 15.5,
      manufacturingProcess: 'CNC Milling & Assembly',
    },
    certifications: [
      { name: 'CE', issuer: 'TÜV SÜD', documentUrl: '#', validUntil: '2028-12-31' },
      { name: 'FCC', issuer: 'FCC', documentUrl: '#', validUntil: '2029-01-01' },
      { name: 'ISO 14001', issuer: 'BSI', documentUrl: '#', validUntil: '2026-05-20' },
    ],
    packaging: { type: 'Recycled Cardboard', recyclable: true, weight: 55, recycledContent: 100 },
    lifecycle: {
      carbonFootprint: 25.5,
      repairabilityScore: 8,
      expectedLifespan: 5,
      energyEfficiencyClass: 'A',
    },
    battery: {
      type: 'Lithium-ion',
      capacityMah: 3110,
      voltage: 3.83,
      isRemovable: false,
    },
    compliance: {
      rohs: { compliant: true },
      ce: { marked: true },
      weee: { registered: true, registrationNumber: 'DE 12345678' },
    },
    sustainability: {
      score: 85,
      environmental: 90,
      social: 80,
      governance: 85,
      summary:
        'Excellent use of recycled materials and strong compliance record. Repairability score is high, contributing positively.',
      isCompliant: true,
      complianceSummary: 'This product is fully compliant with the assigned EU Electronics path.',
      gaps: [],
    },
    customData: {
      internal_sku: 'ECO-SW-S5-BLK',
      is_fragile: true,
    },
    verificationStatus: 'Verified',
    lastVerificationDate: new Date(
      new Date(now).setDate(now.getDate() - 1),
    ).toISOString(),
    endOfLifeStatus: 'Active',
    blockchainProof: {
      type: 'SINGLE_HASH',
      txHash: '0x123abcde1234567890abcdef1234567890',
      explorerUrl: 'https://www.oklink.com/amoy/tx/0x123abcde1234567890abcdef1234567890',
      blockHeight: 123456,
    },
    ebsiDetails: {
      status: 'Verified',
      conformanceResultUrl: 'https://api.ebsi.eu/conformance/v4/results/12345',
    },
    verifiableCredential: `{"@context": ["https://www.w3.org/2018/credentials/v1"],"id": "urn:uuid:mock-vc-id","type": ["VerifiableCredential", "DigitalProductPassport"],"issuer": "did:web:norruva.com","issuanceDate": "${new Date().toISOString()}","credentialSubject": {"id": "did:dpp:product:pp-001","name": "Eco-Friendly Smart Watch Series 5"}}`,
    zkProof: {
      proofData: 'zk_proof_data_string_for_product_001...',
      isVerified: true,
      verifiedAt: new Date().toISOString(),
    },
    ownershipNft: {
      tokenId: '101',
      contractAddress: '0xabcdef...1234',
      ownerAddress: '0xowner...5678',
    },
    chainOfCustody: [
      { date: new Date(Date.now() - 5*24*60*60*1000).toISOString(), event: 'Manufactured', location: 'Germany', actor: 'Eco Innovate Ltd.' },
      { date: new Date(Date.now() - 3*24*60*60*1000).toISOString(), event: 'Shipped', location: 'Hamburg Port', actor: 'DHL' },
    ],
    isMinting: false,
    transit: {
      stage: 'Cleared - Inland Transit (DE)',
      eta: new Date(new Date(now).setDate(now.getDate() + 2)).toISOString(),
      transport: 'Truck',
      origin: 'Poland',
      destination: 'Germany',
      departureDate: new Date(new Date(now).setDate(now.getDate() - 3)).toISOString(),
    },
    customs: {
      status: 'Cleared',
      authority: 'German Customs (Zoll)',
      location: 'Port of Gdansk',
      date: new Date(new Date(now).setHours(now.getHours() - 12)).toISOString(),
      notes: 'EORI number mismatch clarified and resolved.',
    },
  },
  {
    id: 'pp-002',
    companyId: 'comp-eco',
    productName: 'Recycled Plastic Drone Casing',
    productDescription:
      'A lightweight and durable drone casing made from 95% post-consumer recycled plastic. Perfect for DIY drone enthusiasts.',
    productImage: 'https://placehold.co/600x400.png',
    category: 'Electronics',
    supplier: 'Eco Innovate Ltd.',
    status: 'Published',
    materials: [
      { name: 'Recycled ABS Plastic', percentage: 95, recycledContent: 95, origin: 'China' },
      { name: 'Steel Screws', percentage: 5, recycledContent: 10, origin: 'Japan' },
    ],
    manufacturing: { facility: 'Shenzhen Plant', country: 'China' },
    compliance: {},
    createdAt: new Date(new Date(now).setDate(now.getDate() - 5)).toISOString(),
    updatedAt: new Date(new Date(now).setDate(now.getDate() - 3)).toISOString(),
    lastUpdated: new Date(
      new Date(now).setDate(now.getDate() - 3),
    ).toISOString(),
    verificationStatus: 'Verified',
    endOfLifeStatus: 'Active',
    isProcessing: false,
    isMinting: false,
  },
  {
    id: 'pp-003',
    companyId: 'comp-thread',
    productName: 'Organic Cotton T-Shirt',
    productDescription:
      'A soft and comfortable t-shirt made from 100% GOTS-certified organic cotton. Fair-trade certified.',
    productImage: 'https://placehold.co/600x400.png',
    category: 'Fashion',
    supplier: 'Sustainable Threads Inc.',
    status: 'Published',
    compliancePathId: 'cp-fashion-01',
    materials: [
      {
        name: 'Organic Cotton',
        percentage: 100,
        recycledContent: 0,
        origin: 'India',
      },
    ],
    manufacturing: { facility: 'Mumbai Textiles', country: 'India' },
    certifications: [
      { name: 'GOTS', issuer: 'Control Union' },
      { name: 'Fair Trade', issuer: 'Fairtrade International' },
    ],
    compliance: {},
    sustainability: {
      score: 92,
      environmental: 95,
      social: 98,
      governance: 82,
      summary:
        'Excellent sustainability profile due to GOTS and Fair Trade certifications. Material is fully biodegradable.',
      isCompliant: true,
      complianceSummary: '',
    },
    createdAt: new Date(
      new Date(now).setDate(now.getDate() - 10),
    ).toISOString(),
    updatedAt: new Date(new Date(now).setDate(now.getDate() - 4)).toISOString(),
    lastUpdated: new Date(
      new Date(now).setDate(now.getDate() - 4),
    ).toISOString(),
    verificationStatus: 'Pending',
    endOfLifeStatus: 'Active',
    isProcessing: false,
    isMinting: false,
    transit: {
      stage: 'At Customs (Rotterdam, NL)',
      eta: new Date(new Date(now).setDate(now.getDate() + 5)).toISOString(),
      transport: 'Ship',
      origin: 'India',
      destination: 'Netherlands',
      departureDate: new Date(new Date(now).setDate(now.getDate() - 20)).toISOString(),
    },
    customs: {
      status: 'Detained',
      authority: 'Dutch Customs (Douane)',
      location: 'Port of Rotterdam',
      date: new Date(new Date(now).setDate(now.getDate() - 1)).toISOString(),
      notes: 'Awaiting CBAM declaration.',
    },
  },
  {
    id: 'pp-004',
    companyId: 'comp-thread',
    productName: 'Leather Handbag',
    productDescription:
      'A stylish handbag made from Italian leather. Contains lead-based dyes which are non-compliant.',
    productImage: 'https://placehold.co/600x400.png',
    category: 'Fashion',
    supplier: 'Sustainable Threads Inc.',
    status: 'Published',
    compliancePathId: 'cp-fashion-02',
    materials: [
      { name: 'Leather', origin: 'Brazil' },
      { name: 'Lead-based dye' },
    ],
    manufacturing: { facility: 'Milan Leathers', country: 'Italy' },
    compliance: { eudr: { compliant: false }, reach: { svhcDeclared: false } },
    createdAt: new Date(
      new Date(now).setDate(now.getDate() - 15),
    ).toISOString(),
    updatedAt: new Date(new Date(now).setDate(now.getDate() - 5)).toISOString(),
    lastUpdated: new Date(
      new Date(now).setDate(now.getDate() - 5),
    ).toISOString(),
    verificationStatus: 'Failed',
    lastVerificationDate: new Date(
      new Date(now).setDate(now.getDate() - 2),
    ).toISOString(),
    endOfLifeStatus: 'Active',
    sustainability: {
      score: 30,
      environmental: 20,
      social: 50,
      governance: 40,
      isCompliant: false,
      complianceSummary: 'Product contains a banned material: \'Lead-based dye\'.',
      gaps: [
        {
          regulation: 'Global Organic Textile Standard',
          issue: "Product contains a banned material: 'Lead-based dye'",
        },
      ],
    },
    isProcessing: false,
    isMinting: false,
    transit: {
      stage: 'Airborne - Approaching EU',
      eta: new Date(new Date(now).setDate(now.getDate() + 1)).toISOString(),
      transport: 'Plane',
      origin: 'China',
      destination: 'France',
      departureDate: new Date(new Date(now).setHours(now.getHours() - 18)).toISOString(),
    },
  },
  {
    id: 'pp-005',
    companyId: 'comp-eco',
    productName: 'Pro-Grade 4K Drone',
    productDescription:
      'A professional-grade quadcopter with a 4K camera and 30-minute flight time. Submitted for review.',
    productImage: 'https://placehold.co/600x400.png',
    category: 'Electronics',
    supplier: 'Eco Innovate Ltd.',
    status: 'Published',
    materials: [
      { name: 'Carbon Fiber', origin: 'Japan' },
      { name: 'Plastic', origin: 'South Korea' },
      { name: 'Lithium Battery', origin: 'China' },
    ],
    manufacturing: { facility: 'Aero Plant 1', country: 'USA' },
    compliance: {},
    createdAt: new Date(new Date(now).setDate(now.getDate() - 8)).toISOString(),
    updatedAt: new Date(
      new Date(now).setHours(now.getHours() - 12),
    ).toISOString(),
    lastUpdated: new Date(
      new Date(now).setHours(now.getHours() - 12),
    ).toISOString(),
    verificationStatus: 'Pending',
    endOfLifeStatus: 'Active',
    isProcessing: false,
    isMinting: false,
    transit: {
      stage: 'Awaiting Customs Clearance (Antwerp, BE)',
      eta: new Date(new Date(now).setDate(now.getDate() + 1)).toISOString(),
      transport: 'Ship',
      origin: 'Vietnam',
      destination: 'France',
      departureDate: new Date(new Date(now).setDate(now.getDate() - 14)).toISOString(),
    },
  },
  {
    id: 'pp-006',
    companyId: 'comp-eco',
    productName: 'Non-Compliant Power Bank',
    productDescription:
      'A portable power bank with missing compliance data for key EU regulations.',
    productImage: 'https://placehold.co/600x400.png',
    category: 'Electronics',
    supplier: 'Eco Innovate Ltd.',
    status: 'Published',
    compliancePathId: 'cp-electronics-01',
    materials: [{ name: 'Lithium Battery', origin: 'USA' }, { name: 'Plastic Casing', origin: 'USA' }],
    manufacturing: { facility: 'Newark Electronics', country: 'USA' },
    compliance: { rohs: { compliant: false }, weee: { registered: false } },
    createdAt: new Date(
      new Date(now).setDate(now.getDate() - 1),
    ).toISOString(),
    updatedAt: new Date(
      new Date(now).setHours(now.getHours() - 1),
    ).toISOString(),
    lastUpdated: new Date(
      new Date(now).setHours(now.getHours() - 1),
    ).toISOString(),
    verificationStatus: 'Failed',
    lastVerificationDate: new Date().toISOString(),
    endOfLifeStatus: 'Active',
    isProcessing: false,
    isMinting: false,
    sustainability: {
      score: 40,
      environmental: 35,
      social: 50,
      governance: 55,
      complianceSummary: 'Product has multiple compliance failures.',
      isCompliant: false,
      gaps: [],
    },
    transit: {
      stage: 'Pre-Arrival Notification Submitted (Bremerhaven, DE)',
      eta: new Date(new Date(now).setDate(now.getDate() + 15)).toISOString(),
      transport: 'Ship',
      origin: 'USA',
      destination: 'Germany',
      departureDate: new Date(new Date(now).setDate(now.getDate() - 1)).toISOString(),
    },
  },
  {
    id: 'pp-007',
    companyId: 'comp-norruva',
    productName: 'Norruva Platform Dev Laptop',
    productDescription: 'High-performance laptop for Norruva developers.',
    productImage: 'https://placehold.co/600x400.png',
    category: 'Electronics',
    supplier: 'Norruva Corp',
    status: 'Published',
    compliancePathId: 'cp-us-electronics-01',
    materials: [{ name: 'Aluminum', origin: 'Canada' }, { name: 'Silicon', origin: 'USA' }],
    manufacturing: { facility: 'Austin Factory', country: 'USA' },
    compliance: { rohs: { compliant: true }, ce: { marked: true } },
    createdAt: new Date(new Date(now).setDate(now.getDate() - 20)).toISOString(),
    updatedAt: new Date(new Date(now).setDate(now.getDate() - 1)).toISOString(),
    lastUpdated: new Date(new Date(now).setDate(now.getDate() - 1)).toISOString(),
    verificationStatus: 'Verified',
    lastVerificationDate: new Date(new Date(now).setDate(now.getDate() - 1)).toISOString(),
    endOfLifeStatus: 'Active',
  },
  {
    id: 'pp-008',
    companyId: 'comp-buildright',
    productName: 'Eco-Crete Concrete Mix',
    productDescription: 'Low-carbon concrete mix using 40% fly ash replacement.',
    productImage: 'https://placehold.co/600x400.png',
    category: 'Construction',
    supplier: 'BuildRight Inc.',
    status: 'Published',
    compliancePathId: 'cp-construction-eu-01',
    materials: [
      { name: 'Portland Cement', percentage: 50 },
      { name: 'Fly Ash', percentage: 40, recycledContent: 100 },
      { name: 'Aggregate', percentage: 10 },
    ],
    manufacturing: { facility: 'Heidelberg Cement', country: 'Germany', manufacturingProcess: 'Clinker Grinding' },
    createdAt: new Date(new Date(now).setDate(now.getDate() - 5)).toISOString(),
    updatedAt: new Date(new Date(now).setDate(now.getDate() - 2)).toISOString(),
    lastUpdated: new Date(new Date(now).setDate(now.getDate() - 2)).toISOString(),
    verificationStatus: 'Verified',
    lastVerificationDate: new Date(new Date(now).setDate(now.getDate() - 1)).toISOString(),
    endOfLifeStatus: 'Active',
  },
  {
    id: 'pp-009',
    companyId: 'comp-freshfoods',
    productName: 'Organic Apple Juice',
    productDescription: '100% pure organic apple juice, not from concentrate. Packaged in recycled glass.',
    productImage: 'https://placehold.co/600x400.png',
    category: 'Food & Beverage',
    supplier: 'FreshFoods Co.',
    status: 'Draft',
    materials: [
      { name: 'Organic Apples', origin: 'USA' },
      { name: 'Recycled Glass', recycledContent: 80 },
    ],
    manufacturing: { facility: 'Fresno Bottling', country: 'USA' },
    compliance: { foodContact: { safe: true, standard: 'FDA 21 CFR 175' } },
    createdAt: new Date(new Date(now).setDate(now.getDate() - 3)).toISOString(),
    updatedAt: new Date(new Date(now).setHours(now.getHours() - 4)).toISOString(),
    lastUpdated: new Date(new Date(now).setHours(now.getHours() - 4)).toISOString(),
    verificationStatus: 'Not Submitted',
    endOfLifeStatus: 'Active',
  }
];
