
// src/lib/data.ts
import type { Product, BlockchainProof } from '@/types';

const now = new Date();
export let products: Product[] = [
  {
    id: 'pp-001',
    companyId: 'comp-eco',
    gtin: '09501101530003',
    productName: 'Eco-Friendly Smart Watch Series 5',
    productDescription:
      'A state-of-the-art smart watch made from 100% recycled aluminum and ethically sourced components. Features advanced health tracking and a 3-day battery life.',
    productImage: 'https://placehold.co/600x400.png',
    category: 'Electronics',
    supplier: 'Eco Innovate Ltd.',
    status: 'Published',
    compliancePathId: 'cp-electronics-01',
    manualUrl: 'https://example.com/manual.pdf',
    manualFileName: 'smartwatch-manual-v5.pdf',
    manualFileSize: 1258291,
    manualFileHash: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
    // Point to a public GLB file for the 3D model
    model3dUrl: 'https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/DamagedHelmet/glTF-Binary/DamagedHelmet.glb',
    modelHotspots: [
      { position: [0, 0.5, 0], data: { name: 'Visor', material: 'Reinforced Glass' }, interactionType: 'showInfo' },
      { position: [0.5, 0, 0], data: { name: 'Side Panel', material: 'Composite Weave' }, interactionType: 'showInfo' },
    ],
    createdAt: new Date(new Date(now).setDate(now.getDate() - 2)).toISOString(),
    updatedAt: new Date(new Date(now).setDate(now.getDate() - 1)).toISOString(),
    lastUpdated: new Date(
      new Date(now).setDate(now.getDate() - 1),
    ).toISOString(),
    materials: [
      {
        name: 'Recycled Aluminum',
        percentage: 60,
        recycledContent: 100,
        origin: 'Germany',
      },
      {
        name: 'Gorilla Glass',
        percentage: 15,
        recycledContent: 0,
        origin: 'USA',
      },
      {
        name: 'Silicone',
        percentage: 25,
        recycledContent: 50,
        origin: 'South Korea',
      },
    ],
    manufacturing: {
      facility: 'Eco-Factory 1',
      country: 'Germany',
    },
    certifications: [
      { name: 'CE', issuer: 'TÜV SÜD' },
      { name: 'FCC', issuer: 'FCC' },
      { name: 'ISO 14001', issuer: 'BSI' },
    ],
    packaging: { type: 'Recycled Cardboard', recyclable: true },
    lifecycle: {
      carbonFootprint: 25.5,
      carbonFootprintMethod: 'ISO 14067',
      repairabilityScore: 8,
      expectedLifespan: 5,
    },
    battery: {
      type: 'Lithium-ion',
      capacityMah: 3110,
      voltage: 3.83,
      isRemovable: false,
    },
    compliance: {
      rohs: { compliant: true },
      ce: { marked: true },
      weee: { registered: true, registrationNumber: 'DE 12345678' },
    },
    sustainability: {
      score: 85,
      environmental: 90,
      social: 80,
      governance: 85,
      summary:
        'Excellent use of recycled materials and strong compliance record. Repairability score is high, contributing positively.',
      isCompliant: true,
      complianceSummary: 'This product is fully compliant with the assigned EU Electronics path.',
      gaps: [],
    },
    customData: {
      internal_sku: 'ECO-SW-S5-BLK',
      is_fragile: true,
    },
    verificationStatus: 'Verified',
    lastVerificationDate: new Date(
      new Date(now).setDate(now.getDate() - 1),
    ).toISOString(),
    endOfLifeStatus: 'Active',
    blockchainProof: {
      type: 'SINGLE_HASH',
      chain: 'Polygon',
      txHash: '0x123abcde1234567890abcdef1234567890',
      explorerUrl: 'https://www.oklink.com/amoy/tx/0x123abcde1234567890abcdef1234567890',
      blockHeight: 123456,
    },
    serviceHistory: [
      {
        id: 'serv-001',
        providerId: 'user-service',
        providerName: 'Official Repair Service',
        notes: 'Replaced battery under warranty. Firmware updated to v2.1.',
        createdAt: new Date(new Date(now).setDate(now.getDate() - 100)).toISOString(),
        updatedAt: new Date(new Date(now).setDate(now.getDate() - 100)).toISOString(),
      },
    ],
    customs: {
      status: 'Cleared',
      authority: 'German Customs (Zoll)',
      location: 'Frankfurt (Oder)',
      date: new Date().toISOString(),
      notes: 'Random inspection passed without issues.'
    },
  },
  {
    id: 'pp-002',
    companyId: 'comp-eco',
    productName: 'Recycled Plastic Drone Casing',
    productDescription:
      'A lightweight and durable drone casing made from 95% post-consumer recycled plastic. Perfect for DIY drone enthusiasts.',
    productImage: 'https://placehold.co/600x400.png',
    category: 'Electronics',
    supplier: 'Eco Innovate Ltd.',
    status: 'Published',
    materials: [
      { name: 'Recycled ABS Plastic', percentage: 95, recycledContent: 95, origin: 'China' },
      { name: 'Steel Screws', percentage: 5, recycledContent: 10, origin: 'Japan' },
    ],
    manufacturing: { facility: 'Shenzhen Plant', country: 'China' },
    compliance: {},
    createdAt: new Date(new Date(now).setDate(now.getDate() - 5)).toISOString(),
    updatedAt: new Date(new Date(now).setDate(now.getDate() - 3)).toISOString(),
    lastUpdated: new Date(
      new Date(now).setDate(now.getDate() - 3),
    ).toISOString(),
    verificationStatus: 'Verified',
    endOfLifeStatus: 'Active',
  },
  {
    id: 'pp-003',
    companyId: 'comp-thread',
    productName: 'Organic Cotton T-Shirt',
    productDescription:
      'A soft and comfortable t-shirt made from 100% GOTS-certified organic cotton. Fair-trade certified.',
    productImage: 'https://placehold.co/600x400.png',
    category: 'Fashion',
    supplier: 'Sustainable Threads Inc.',
    status: 'Published',
    compliancePathId: 'cp-fashion-01',
    materials: [
      {
        name: 'Organic Cotton',
        percentage: 100,
        recycledContent: 0,
        origin: 'India',
      },
    ],
    textile: {
      fiberComposition: [{ name: 'Organic Cotton', percentage: 100 }],
      dyeProcess: 'Low-impact fiber-reactive dyes',
      weaveType: 'Jersey Knit',
    },
    manufacturing: { facility: 'Mumbai Textiles', country: 'India' },
    certifications: [
      { name: 'GOTS', issuer: 'Control Union' },
      { name: 'Fair Trade', issuer: 'Fairtrade International' },
    ],
    compliance: {},
    sustainability: {
      score: 92,
      environmental: 95,
      social: 98,
      governance: 82,
      summary:
        'Excellent sustainability profile due to GOTS and Fair Trade certifications. Material is fully biodegradable.',
      isCompliant: true,
      complianceSummary: '',
    },
    createdAt: new Date(
      new Date(now).setDate(now.getDate() - 10),
    ).toISOString(),
    updatedAt: new Date(new Date(now).setDate(now.getDate() - 4)).toISOString(),
    lastUpdated: new Date(
      new Date(now).setDate(now.getDate() - 4),
    ).toISOString(),
    verificationStatus: 'Pending',
    endOfLifeStatus: 'Active',
    customs: {
      status: 'Detained',
      authority: 'Dutch Customs',
      location: 'Port of Rotterdam',
      date: new Date().toISOString(),
      notes: 'Awaiting CBAM declaration for textile import.',
    },
  },
  {
    id: 'pp-004',
    companyId: 'comp-thread',
    productName: 'Leather Handbag',
    productDescription:
      'A stylish handbag made from Italian leather. Contains lead-based dyes which are non-compliant.',
    productImage: 'https://placehold.co/600x400.png',
    category: 'Fashion',
    supplier: 'Sustainable Threads Inc.',
    status: 'Published',
    compliancePathId: 'cp-fashion-02',
    materials: [
      { name: 'Leather', origin: 'Brazil' },
      { name: 'Lead-based dye' },
    ],
    manufacturing: { facility: 'Milan Leathers', country: 'Italy' },
    compliance: { eudr: { compliant: false }, reach: { svhcDeclared: false } },
    createdAt: new Date(
      new Date(now).setDate(now.getDate() - 15),
    ).toISOString(),
    updatedAt: new Date(new Date(now).setDate(now.getDate() - 5)).toISOString(),
    lastUpdated: new Date(
      new Date(now).setDate(now.getDate() - 5),
    ).toISOString(),
    verificationStatus: 'Failed',
    lastVerificationDate: new Date(
      new Date(now).setDate(now.getDate() - 2),
    ).toISOString(),
    endOfLifeStatus: 'Recycled',
    sustainability: {
      score: 30,
      environmental: 20,
      social: 50,
      governance: 40,
      isCompliant: false,
      complianceSummary: 'Product fails on two counts: contains a banned substance (Lead) and lacks a valid EUDR declaration for the leather origin.',
      gaps: [
        {
          regulation: 'EUDR',
          issue: 'Product does not have a valid EU Deforestation-Free Regulation declaration.',
        },
        {
          regulation: 'REACH',
          issue: "Product contains a banned material: 'Lead-based dye'",
        },
      ],
    },
  },
  {
    id: 'pp-005',
    companyId: 'comp-eco',
    productName: 'Pro-Grade 4K Drone',
    productDescription:
      'A professional-grade quadcopter with a 4K camera and 30-minute flight time. Submitted for review.',
    productImage: 'https://placehold.co/600x400.png',
    category: 'Electronics',
    supplier: 'Eco Innovate Ltd.',
    status: 'Published',
    materials: [
      { name: 'Carbon Fiber', origin: 'Japan' },
      { name: 'Plastic', origin: 'South Korea' },
      { name: 'Lithium Battery', origin: 'China' },
    ],
    manufacturing: { facility: 'Aero Plant 1', country: 'USA' },
    compliance: {},
    createdAt: new Date(new Date(now).setDate(now.getDate() - 8)).toISOString(),
    updatedAt: new Date(
      new Date(now).setHours(now.getHours() - 12),
    ).toISOString(),
    lastUpdated: new Date(
      new Date(now).setHours(now.getHours() - 12),
    ).toISOString(),
    verificationStatus: 'Pending',
    endOfLifeStatus: 'Active',
  },
  {
    id: 'pp-006',
    companyId: 'comp-eco',
    productName: 'Non-Compliant Power Bank',
    productDescription:
      'A portable power bank with missing compliance data for key EU regulations.',
    productImage: 'https://placehold.co/600x400.png',
    category: 'Electronics',
    supplier: 'Eco Innovate Ltd.',
    status: 'Published',
    compliancePathId: 'cp-electronics-01',
    materials: [{ name: 'Lithium Battery', origin: 'USA' }, { name: 'Plastic Casing', origin: 'USA' }],
    manufacturing: { facility: 'Newark Electronics', country: 'USA' },
    compliance: { rohs: { compliant: false }, weee: { registered: false } },
    createdAt: new Date(
      new Date(now).setDate(now.getDate() - 1),
    ).toISOString(),
    updatedAt: new Date(
      new Date(now).setHours(now.getHours() - 1),
    ).toISOString(),
    lastUpdated: new Date(
      new Date(now).setHours(now.getHours() - 1),
    ).toISOString(),
    verificationStatus: 'Failed',
    lastVerificationDate: new Date().toISOString(),
    endOfLifeStatus: 'Active',
    sustainability: {
      score: 40,
      environmental: 35,
      social: 50,
      governance: 55,
      complianceSummary: 'Product has multiple compliance failures.',
      isCompliant: false,
      gaps: [],
    },
    customs: {
      status: 'Rejected',
      authority: 'German Customs (Zoll)',
      location: 'Port of Bremerhaven',
      date: new Date(new Date(now).setHours(now.getHours() - 2)).toISOString(),
      notes: 'Shipment rejected due to non-compliance with EU WEEE regulations. Return to sender initiated.',
    },
  },
  {
    id: 'pp-007',
    companyId: 'comp-norruva',
    productName: 'Bamboo Serving Tray',
    productDescription: 'A serving tray made from sustainable bamboo, perfect for any occasion.',
    productImage: 'https://placehold.co/600x400.png',
    category: 'Home Goods',
    supplier: 'Norruva Corp',
    status: 'Draft',
    materials: [{ name: 'Bamboo', percentage: 100, origin: 'China' }],
    createdAt: new Date(new Date(now).setHours(now.getHours() - 10)).toISOString(),
    updatedAt: new Date(new Date(now).setHours(now.getHours() - 2)).toISOString(),
    lastUpdated: new Date(new Date(now).setHours(now.getHours() - 2)).toISOString(),
    verificationStatus: 'Not Submitted',
    endOfLifeStatus: 'Active',
  },
  {
    id: 'pp-008',
    companyId: 'comp-buildright',
    productName: 'Eco-Crete Concrete Mix',
    productDescription: 'A low-carbon concrete mix using recycled aggregate and fly ash.',
    productImage: 'https://placehold.co/600x400.png',
    category: 'Construction',
    supplier: 'BuildRight Inc.',
    status: 'Published',
    compliancePathId: 'cp-construction-eu-01',
    materials: [
      { name: 'Portland Cement', percentage: 25 },
      { name: 'Recycled Aggregate', percentage: 50, recycledContent: 100 },
      { name: 'Fly Ash', percentage: 25 },
    ],
    manufacturing: {
      facility: 'Heidelberg Plant',
      country: 'Germany',
      manufacturingProcess: 'Cold-mix process',
    },
    createdAt: new Date(new Date(now).setDate(now.getDate() - 30)).toISOString(),
    updatedAt: new Date(new Date(now).setDate(now.getDate() - 3)).toISOString(),
    lastUpdated: new Date(new Date(now).setDate(now.getDate() - 3)).toISOString(),
    verificationStatus: 'Verified',
    lastVerificationDate: new Date(new Date(now).setDate(now.getDate() - 3)).toISOString(),
    endOfLifeStatus: 'Active',
  },
  {
    id: 'pp-009',
    companyId: 'comp-freshfoods',
    productName: 'Organic Tomato Sauce',
    productDescription: 'A classic tomato sauce made with 100% organic Italian tomatoes.',
    productImage: 'https://placehold.co/600x400.png',
    category: 'Food & Beverage',
    supplier: 'FreshFoods Co.',
    status: 'Published',
    compliancePathId: 'cp-global-food-contact-01',
    foodSafety: {
      ingredients: [{ value: 'Organic Tomatoes' }, { value: 'Water' }, { value: 'Organic Basil' }],
      allergens: 'None.',
    },
    packaging: { type: 'Glass Jar, Steel Lid', recyclable: true },
    createdAt: new Date(new Date(now).setDate(now.getDate() - 5)).toISOString(),
    updatedAt: new Date(new Date(now).setDate(now.getDate() - 2)).toISOString(),
    lastUpdated: new Date(new Date(now).setDate(now.getDate() - 2)).toISOString(),
    verificationStatus: 'Verified',
    lastVerificationDate: new Date(new Date(now).setDate(now.getDate() - 2)).toISOString(),
    endOfLifeStatus: 'Active',
  },
];

    