// src/lib/integration-data.ts
import type { Integration } from '@/types';

const now = new Date();

export let integrations: Integration[] = [
  {
    id: 'int-sap',
    name: 'SAP S/4HANA',
    type: 'ERP',
    logo: 'https://placehold.co/40x40.png',
    dataAiHint: 'sap logo',
    description: 'Sync product data, bill of materials, and supply chain information.',
    enabled: true,
    status: 'Connected',
    lastSync: new Date(new Date(now).setHours(now.getHours() - 1)).toISOString(),
    recordsSynced: 2348,
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
  },
  {
    id: 'int-oracle',
    name: 'Oracle NetSuite',
    type: 'ERP',
    logo: 'https://placehold.co/40x40.png',
    dataAiHint: 'oracle logo',
    description: 'Automate DPP creation from NetSuite item records.',
    enabled: false,
    status: 'Disconnected',
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
  },
  {
    id: 'int-dynamics',
    name: 'Microsoft Dynamics 365',
    type: 'ERP',
    logo: 'https://placehold.co/40x40.png',
    dataAiHint: 'microsoft logo',
    description: 'Connect your business data from the Dynamics 365 ecosystem.',
    enabled: true,
    status: 'Error',
    lastSync: new Date(new Date(now).setDate(now.getDate() - 1)).toISOString(),
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
  },
  {
    id: 'int-siemens',
    name: 'Siemens Teamcenter',
    type: 'PLM',
    logo: 'https://placehold.co/40x40.png',
    dataAiHint: 'siemens logo',
    description: 'Link engineering and design data from Teamcenter.',
    enabled: false,
    status: 'Disconnected',
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
  },
  {
    id: 'int-shopify',
    name: 'Shopify',
    type: 'E-commerce',
    logo: 'https://placehold.co/40x40.png',
    dataAiHint: 'shopify logo',
    description: 'Embed DPP QR codes on your Shopify product pages.',
    enabled: true,
    status: 'Connected',
    lastSync: new Date(new Date(now).setMinutes(now.getMinutes() - 15)).toISOString(),
    recordsSynced: 58,
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
  },
  {
    id: 'int-salesforce',
    name: 'Salesforce',
    type: 'CRM',
    logo: 'https://placehold.co/40x40.png',
    dataAiHint: 'salesforce logo',
    description: 'Link product data to customer accounts and service cases.',
    enabled: false,
    status: 'Disconnected',
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
  },
  {
    id: 'int-gdrive',
    name: 'Google Drive',
    type: 'Cloud Storage',
    logo: 'https://placehold.co/40x40.png',
    dataAiHint: 'google drive logo',
    description: 'Automatically import compliance documents and certificates.',
    enabled: true,
    status: 'Connected',
    lastSync: new Date(new Date(now).setHours(now.getHours() - 3)).toISOString(),
    recordsSynced: 142,
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
  },
  {
    id: 'int-tableau',
    name: 'Tableau',
    type: 'Analytics',
    logo: 'https://placehold.co/40x40.png',
    dataAiHint: 'tableau logo',
    description: 'Push DPP data to Tableau for advanced business intelligence.',
    enabled: false,
    status: 'Disconnected',
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
  },
];
