
// src/lib/user-data.ts
import type { User } from '@/types';
import { UserRoles } from './constants';

const now = new Date();

export let users: User[] = [
  {
    id: 'user-admin',
    fullName: 'Admin User',
    email: 'admin@norruva.com',
    avatarUrl: 'https://i.pravatar.cc/150?u=user-admin',
    companyId: 'comp-norruva',
    roles: Object.values(UserRoles),
    createdAt: new Date(new Date(now).setMonth(now.getMonth() - 1)).toISOString(),
    updatedAt: new Date(new Date(now).setMonth(now.getMonth() - 1)).toISOString(),
    onboardingComplete: true,
    isMfaEnabled: false,
    readNotificationIds: [],
    circularityCredits: 5,
    notificationPreferences: {
      productUpdates: true,
      complianceAlerts: true,
      platformNews: true,
    },
  },
  {
    id: 'user-supplier',
    fullName: 'Supplier User',
    email: 'supplier@norruva.com',
    avatarUrl: 'https://i.pravatar.cc/150?u=user-supplier',
    companyId: 'comp-eco',
    roles: [UserRoles.SUPPLIER],
    createdAt: new Date(new Date(now).setMonth(now.getMonth() - 1)).toISOString(),
    updatedAt: new Date(new Date(now).setMonth(now.getMonth() - 1)).toISOString(),
    onboardingComplete: true,
    isMfaEnabled: false,
    readNotificationIds: [],
    circularityCredits: 0,
    notificationPreferences: {
      productUpdates: true,
      complianceAlerts: false,
      platformNews: false,
    },
  },
  {
    id: 'user-auditor',
    fullName: 'Auditor User',
    email: 'auditor@norruva.com',
    avatarUrl: 'https://i.pravatar.cc/150?u=user-auditor',
    companyId: 'comp-norruva',
    roles: [UserRoles.AUDITOR],
    createdAt: new Date(new Date(now).setMonth(now.getMonth() - 1)).toISOString(),
    updatedAt: new Date(new Date(now).setMonth(now.getMonth() - 1)).toISOString(),
    onboardingComplete: true,
    isMfaEnabled: false,
    readNotificationIds: [],
    circularityCredits: 0,
    notificationPreferences: {
      productUpdates: true,
      complianceAlerts: true,
      platformNews: false,
    },
  },
  {
    id: 'user-compliance',
    fullName: 'Compliance Manager',
    email: 'compliance@norruva.com',
    avatarUrl: 'https://i.pravatar.cc/150?u=user-compliance',
    companyId: 'comp-norruva',
    roles: [UserRoles.COMPLIANCE_MANAGER],
    createdAt: new Date(new Date(now).setMonth(now.getMonth() - 1)).toISOString(),
    updatedAt: new Date(new Date(now).setMonth(now.getMonth() - 1)).toISOString(),
    onboardingComplete: true,
    isMfaEnabled: false,
    readNotificationIds: [],
    circularityCredits: 0,
    notificationPreferences: {
      productUpdates: true,
      complianceAlerts: true,
      platformNews: true,
    },
  },
  {
    id: 'user-manufacturer',
    fullName: 'Manufacturer User',
    email: 'manufacturer@norruva.com',
    avatarUrl: 'https://i.pravatar.cc/150?u=user-manufacturer',
    companyId: 'comp-eco',
    roles: [UserRoles.MANUFACTURER],
    createdAt: new Date(new Date(now).setMonth(now.getMonth() - 1)).toISOString(),
    updatedAt: new Date(new Date(now).setMonth(now.getMonth() - 1)).toISOString(),
    onboardingComplete: true,
    isMfaEnabled: false,
    readNotificationIds: [],
    circularityCredits: 0,
    notificationPreferences: {
      productUpdates: true,
      complianceAlerts: false,
      platformNews: false,
    },
  },
  {
    id: 'user-service',
    fullName: 'Service Provider',
    email: 'service@norruva.com',
    avatarUrl: 'https://i.pravatar.cc/150?u=user-service',
    companyId: 'comp-norruva',
    roles: [UserRoles.SERVICE_PROVIDER],
    createdAt: new Date(new Date(now).setMonth(now.getMonth() - 1)).toISOString(),
    updatedAt: new Date(new Date(now).setMonth(now.getMonth() - 1)).toISOString(),
    onboardingComplete: true,
    isMfaEnabled: false,
    readNotificationIds: [],
    circularityCredits: 0,
    notificationPreferences: {
      productUpdates: false,
      complianceAlerts: false,
      platformNews: false,
    },
  },
  {
    id: 'user-recycler',
    fullName: 'Recycler User',
    email: 'recycler@norruva.com',
    avatarUrl: 'https://i.pravatar.cc/150?u=user-recycler',
    companyId: 'comp-norruva',
    roles: [UserRoles.RECYCLER],
    createdAt: new Date(new Date(now).setMonth(now.getMonth() - 1)).toISOString(),
    updatedAt: new Date(new Date(now).setMonth(now.getMonth() - 1)).toISOString(),
    onboardingComplete: true,
    isMfaEnabled: false,
    readNotificationIds: [],
    circularityCredits: 20,
    notificationPreferences: {
      productUpdates: false,
      complianceAlerts: false,
      platformNews: false,
    },
  },
  {
    id: 'user-retailer',
    fullName: 'Retailer User',
    email: 'retailer@norruva.com',
    avatarUrl: 'https://i.pravatar.cc/150?u=user-retailer',
    companyId: 'comp-norruva',
    roles: [UserRoles.RETAILER],
    createdAt: new Date(new Date(now).setMonth(now.getMonth() - 1)).toISOString(),
    updatedAt: new Date(new Date(now).setMonth(now.getMonth() - 1)).toISOString(),
    onboardingComplete: true,
    isMfaEnabled: false,
    readNotificationIds: [],
    circularityCredits: 0,
    notificationPreferences: {
      productUpdates: true,
      complianceAlerts: false,
      platformNews: true,
    },
  },
  {
    id: 'user-developer',
    fullName: 'Developer User',
    email: 'developer@norruva.com',
    avatarUrl: 'https://i.pravatar.cc/150?u=user-developer',
    companyId: 'comp-norruva',
    roles: [UserRoles.DEVELOPER],
    createdAt: new Date(new Date(now).setMonth(now.getMonth() - 1)).toISOString(),
    updatedAt: new Date(new Date(now).setMonth(now.getMonth() - 1)).toISOString(),
    onboardingComplete: true,
    isMfaEnabled: false,
    readNotificationIds: [],
    circularityCredits: 0,
    notificationPreferences: {
      productUpdates: false,
      complianceAlerts: true,
      platformNews: true,
    },
  },
  {
    id: 'user-analyst',
    fullName: 'Business Analyst',
    email: 'analyst@norruva.com',
    avatarUrl: 'https://i.pravatar.cc/150?u=user-analyst',
    companyId: 'comp-norruva',
    roles: [UserRoles.BUSINESS_ANALYST],
    createdAt: new Date(new Date(now).setMonth(now.getMonth() - 1)).toISOString(),
    updatedAt: new Date(new Date(now).setMonth(now.getMonth() - 1)).toISOString(),
    onboardingComplete: true,
    isMfaEnabled: false,
    readNotificationIds: [],
    circularityCredits: 0,
    notificationPreferences: {
      productUpdates: true,
      complianceAlerts: true,
      platformNews: false,
    },
  },
];
